LMS/urls.py
from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path
from rest_framework import routers

from WebApp import api
from WebApp import views
from WebApp.student_module.views import loginforapp, singleUserHomePageJSON, studentCourseProgress

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^rest-auth/', include('rest_auth.urls')),
                  url(r'^quiz/', include('quiz.urls')),
                  # path('', include('WebApp.urls')),
                  # path('', decorator_include([login_required, authorize(lambda u: u.Is_CenterAdmin)], 'WebApp.urls')),
                  # path('students/',decorator_include([login_required, authorize(lambda u: u.Is_Student)], 'WebApp.student_module.urls')),
                  # path('teachers/',decorator_include([login_required, authorize(lambda u: u.Is_Teacher)], 'WebApp.teacher_module.urls')),
                  path('', decorator_include(login_required, 'WebApp.urls')),
                  path('students/', decorator_include(login_required, 'WebApp.student_module.urls')),
                  path('teachers/', decorator_include(login_required, 'WebApp.teacher_module.urls')),
                  path('courseinfo/<int:course>/chapterinfo/<int:chapter>/offline_contents',
                       views.OfflineContentsView.as_view(), name='offlinecontentviewer'),
                  url(r'^$', views.start, name='start'),
                  path('forum/', include('forum.urls')),
                  path('survey/', include('survey.urls')),
                  path('login/', views.login.as_view(), name='login'),
                  #   url(r'^login/$', views.login, {'template_name': 'registration/login.html',
                  #                                  'redirect_authenticated_user': True}, name='login'),
                  path(
                      'students/courseinfo/<int:course>/chapterinfo/<int:chapter>/contentforapp/<slug:username>/<slug:password>/',
                      loginforapp, name='loginforapp'),

                  url(r'^.*logout/$', views.logout,
                      {'template_name': 'registration/logout.html', 'next_page': '/'}, name='logout'),

                  #     url(r'^.*editprofile/$', views.editprofile, name='editprofile'),

                  url(r'^successlogin/$', views.loginsuccess, name='loginsuccess'),

                  url(r'^.*register/$', views.register.as_view(), name='register'),
                  path('ajax/validate_username/', views.validate_username, name='validate_username'),
                  path('ajax/validate_password/', views.validate_password, name='validate_password'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

router = routers.DefaultRouter()

router.register(r'centerinfo', api.CenterInfoViewSet)
router.register(r'memberinfo', api.MemberInfoViewSet)
router.register(r'courseinfo', api.CourseInfoViewSet)
router.register(r'chapterinfo', api.ChapterInfoViewSet)
router.register(r'inninginfo', api.InningInfoViewSet)
router.register(r'sessionmapinfo', api.SessionMapInfoViewSet)
router.register(r'sessioninfo', api.SessionInfoViewSet)
router.register(r'assignassignmentinfo', api.AssignAssignmentInfoViewSet)
router.register(r'inninggroup', api.InningGroupViewSet)
router.register(r'groupmapping', api.GroupMappingViewSet)
router.register(r'assignmentinfo', api.AssignmentInfoViewSet)
router.register(r'assignanswerinfo', api.AssignAnswerInfoViewSet)
router.register(r'questioninfo', api.QuestionInfoViewSet)
router.register(r'attendance', api.AttendanceViewSet)

urlpatterns += [
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
    path('api/v1/chaptercontent/<int:chapterID>', api.ChapterContent.as_view(), name='chaptercontent'),
]

urlpatterns += [
    # urls for chapterpagebuilder
    path('3DViewer/<path:urlpath>',
         views.ThreeDViewer, name='3DViewer'),
    path('3DViewer/',
         views.ThreeDViewer, name='3DViewer'),

    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += [
    # urls for chapterpagebuilder
    path('gitpull', views.gitpull),
]
handler400 = 'WebApp.views.error_400'
handler403 = 'WebApp.views.error_403'
handler404 = 'WebApp.views.error_404'
handler500 = 'WebApp.views.error_500'

urlpatterns += (
    path('pwabuilder-sw.js', views.ServiceWorker),
    path('offline.html', views.OfflineApp),
    path('manifest.webmanifest', views.manifestwebmanifest),
)

# For static files
urlpatterns += (
    path('get_static_files_info/', views.get_static_files_info, name='get_static_files_info'),
    # for downloading static files for mobile development
    path('get_static_files/', views.get_static_files, name='get_static_files'),
    # for downloading static files for mobile development
    path('students/singleUserHomePageAPI/', singleUserHomePageJSON, name='singleUserHomePage'),  # for app
    path('students/homepage/', singleUserHomePageJSON, name='studentHomePage'),  # for app
    path('students/course/<int:coursepk>/progress', studentCourseProgress, name='studentcourseprogressapp'),  # for app

)

# Login URL get
urlpatterns += (
    path('loaderio-954a872bfd2583affa027425d4a0dd5a/', views.loaderverifylink),
    path('loginforappredirect/<slug:username>/<slug:password>/', views.loginforappredirect, name='loginforappredirect'),
)

# For Media Direct Links

urlpatterns += (
    path('api/v1/video_urlresolver/', views.getDirectURLOfMedias, name='getDirectURLOfMedias'),
    path('api/v1/<int:chapterID>/chat_history/', views.getChatMessageHistoryApi, name='getChatHistory'),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls'))
    ]

import Notifications.urls

urlpatterns += (
    url('^inbox/notifications/', include(Notifications.urls, namespace='Notifications')),
)

urlpatterns += (
    path('comment/', include('comment.urls')),
)

urlpatterns += (
    path('admin/log_viewer/', include('log_viewer.urls')),
)

Notifications/urls.py
from distutils.version import StrictVersion

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern

app_name = 'Notifications'

urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^all/', views.SeeAllNotificationsList.as_view(), name='see_all'),
    # pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<pk>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<pk>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<pk>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

forum/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include
from django.urls import path
from rest_framework import routers

from . import api
from . import views

app_name = "forum"
api_router = routers.DefaultRouter()
router = routers.DefaultRouter()
router.register(r'thread', api.ThreadViewSet)
router.register(r'post', api.PostViewSet)
router.register(r'notification', api.NotificationViewSet)
router.register(r'nodegroup', api.NodeGroupViewSet)
router.register(r'topic', api.TopicViewSet)
router.register(r'studentTopic', api.StudnetTopic)

urlpatterns = [
    path(r'^page/(?P<page>[0-9]+)/$', views.Index.as_view(), name='index'),
    path(r'', views.Index.as_view(), name='index'),
    path(r'^topic/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$',
         views.TopicView.as_view(), name='topic'),
    path('topic/<int:pk>/', views.TopicView.as_view(), name='topic'),
    path(r'^nodegroup/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$',
         views.NodeGroupView.as_view(), name='nodegroup'),
    path('nodegroup/<int:pk>/', views.NodeGroupView.as_view(), name='nodegroup'),
    path(r't/edit/<int:pk>/', views.edit_thread, name='edit_thread'),
    path(r'post/edit/<int:pk>/', views.edit_post, name='edit_post'),
    path(r'topic/edit/<int:pk>/', views.edit_topic, name='edit_topic'),
    path(r't/append/<int:pk>/', views.create_appendix, name='create_appendix'),
    path(r'^t/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$',
         views.ThreadView.as_view(), name='thread'),
    path(r't/<int:pk>/', views.ThreadView.as_view(), name='thread'),
    path('ThreadListLoadMoreViewAjax/<int:pk>/<int:count>',
         views.ThreadList_LoadMoreViewAjax, name='Show_More'),
    path(r'u/<int:pk>/', views.user_info, name='user_info'),
    path(r'^u/(?P<pk>\d+)/threads/page/(?P<page>[0-9]+)/$',
         views.UserThreads.as_view(), name='user_threads'),
    path(r'u/threads/<int:pk>/', views.UserThreads.as_view(), name='user_threads'),
    path(r'^u/(?P<pk>\d+)/posts/page/(?P<page>[0-9]+)/$',
         views.UserPosts.as_view(), name='user_posts'),
    path(r'u/posts/<int:pk>/', views.UserPosts.as_view(), name='user_posts'),
    path(r'login/', views.login_view, name='login'),
    path(r'reg/', views.reg_view, name='reg'),
    path(r'logout/', views.logout_view, name="logout"),

    path(r'search/', views.search_redirect, name='search_redirect'),
    path(r'^search/(?P<keyword>.*?)/page/(?P<page>[0-9]+)/$',
         views.SearchView.as_view(), name='search'),
    path(r'search/(?P<keyword>.*)/', views.SearchView.as_view(), name='search'),

    path(r't/create/', views.create_thread, name='create_thread'),
    path(r't/create/(?P<nodegroup_pk>\d+)/',
         views.create_thread, name='create_thread'),
    path(r' t/create/(?P<nodegroup_pk>\d+)/(?P<topic_pk>\d+)/',
         views.create_thread, name='create_thread'),

    path(r'topic/create/', views.create_topic, name='create_topic'),
    path(r'topic/create/(?P<nodegroup_pk>\d+)',
         views.create_topic, name='create_topic'),
    path(r'notifications/', views.NotificationView.as_view(), name='notifications'),
    path(r'avatar/', views.upload_avatar, name="upload_avatar"),

    path('t/create/threadsearchAjax/<int:topic_id>/',
         views.ThreadSearchAjax, name='Admin_thread_search'),
    path(r'api/v1/', include(router.urls)),
]

forum/forms.py
# -*- coding: utf-8 -*-
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.conf import settings
from django.forms import ModelForm, HiddenInput
from django.utils.translation import ugettext as _

from .models import Thread, Appendix, ForumAvatar, Post, Topic

if 'pagedown' in settings.INSTALLED_APPS:
    use_pagedown = True
    from django import forms
    from pagedown.widgets import PagedownWidget
else:
    use_pagedown = False


class ThreadForm(ModelForm):
    if use_pagedown:
        content_raw = forms.CharField(
            label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ThreadForm, self).__init__(*args, **kwargs)
        # self.fields['topic'].queryset = Topic.objects.filter(
        #     center_associated_with=self.user.Center_Code)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Thread
        fields = ['topic', 'title', 'content_raw']
        labels = {
            'content_raw': _('Content'),
            'topic': _('Topic'),
            'title': _('Title'),
        }

    def save(self, commit=True):
        inst = super(ThreadForm, self).save(commit=False)
        inst.user = self.user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ThreadEditForm(ModelForm):
    if use_pagedown:
        content_raw = forms.CharField(
            label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        super(ThreadEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Thread
        fields = ('title', 'content_raw',)
        labels = {
            'content_raw': ('Content'),
        }


class TopicForm(ModelForm):

    if use_pagedown:
        content_raw = forms.CharField(
            label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(TopicForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['topic_icon'].widget = HiddenInput()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Topic
        fields = ['node_group', 'title', 'description', 'topic_icon']
        labels = {
            'node_group': _('NodeGroup'),
            'description': _('Description'),
            'title': _('Title'),
            'topic_icon': _('Topic Icon'),
        }

    def save(self, commit=True):
        inst = super(TopicForm, self).save(commit=False)
        inst.center_associated_with = self.user.Center_Code
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class TopicEditForm(ModelForm):
    if use_pagedown:
        content_raw = forms.CharField(
            label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        super(TopicEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Topic
        fields = ('description', 'topic_icon',)
        labels = {
            'description': _('Description'),
            'topic_icon': _('Topic Icon'),
        }


class AppendixForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.thread = kwargs.pop('thread', None)
        super(AppendixForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Appendix
        fields = ('content_raw',)
        labels = {
            'content_raw': _('Content'),
        }

    def save(self, commit=True):
        inst = super(AppendixForm, self).save(commit=False)
        inst.thread = self.thread
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ForumAvatarForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ForumAvatarForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = ForumAvatar
        fields = ('image', 'use_gravatar')
        labels = {
            'image': _('Avatar Image'),
            'use_gravatar': _("Always Use Gravatar")
        }

    def save(self, commit=True):
        inst = super(ForumAvatarForm, self).save(commit=False)
        inst.user = self.user
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class ReplyForm(ModelForm):
    if use_pagedown:
        content_raw = forms.CharField(label='', widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.thread_id = kwargs.pop('thread_id', None)
        super(ReplyForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Post
        fields = ('content_raw',)
        labels = {
            'content_raw': '',
        }

    def save(self, commit=True):
        inst = super(ReplyForm, self).save(commit=False)
        inst.user = self.user
        inst.thread_id = self.thread_id
        if commit:
            inst.save()
            self.save_m2m()
        return inst


class PostEditForm(ModelForm):
    if use_pagedown:
        content_raw = forms.CharField(
            label=_('Content'), widget=PagedownWidget())

    def __init__(self, *args, **kwargs):
        super(PostEditForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', _('Submit')))

    class Meta:
        model = Post
        fields = ('content_raw',)
        labels = {
            'content_raw': _('Content'),
        }

forum/templates/forum/ThreadSearchAjax.html
{% load i18n %}
{% load forum_tags %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load static %}




{% for thread in RelevantThread %}
<h5>
    <div id="ThreadSearch">
        <a style="color: #1F618D;" href="/forum/t/{{ thread.pk }}">{{ thread.title }}</a><br>
    </div>
</h5>

{% endfor %}

forum/templates/forum/create_appendix.html
{% extends 'forum/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block left %}
    <div class="panel panel-default">
        <div class="panel-body">
            <form method="post" action="{% url "forum:create_appendix" pk=pk %}">
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

forum/templates/forum/edit_post.html
{% extends 'forum/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block main_contain %}
<div class="panel panel-default">
    <div class="panel-body">
        <form method="post" action="{% url 'forum:edit_post' pk=form.instance.pk %}">

            {{ csrf_token }}

            {% crispy form %}


        </form>
    </div>
</div>
{% endblock %}

forum/templates/forum/edit_thread.html
{% extends 'forum/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block breadcrumb %}


<li class="breadcrumb-item"><a href="{% url 'forum:index' %}">Forum</a></li>
<li class="breadcrumb-item active"><a href="{% url 'forum:edit_thread' pk=form.instance.pk %}"> Edit Thread</a>
</li>

{% endblock %}

{% block main_contain %}



<div class="panel-body topic_create" data-z="0.5">
    <form method="post" action="{% url 'forum:edit_thread' pk=form.instance.pk %}">
        {% csrf_token %}


        <div id="div_id_title" class="form-group"> <label for="id_title" class="control-label  requiredField">
                Title<span class="asteriskField">*</span> </label>
            <div class="controls "> <input type="text" name="title" value="{{ object.title }}" maxlength="120"
                    class="textinput textInput form-control" id="id_title" required=""> </div>
        </div>








        <div class="x_panel">
            <div class="x_title">
                <h2>Description

                </h2>

                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div id="alerts"></div>
                <div class="btn-toolbar editor" data-role="editor-toolbar" data-target="#editor-one">
                    <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="fa fa-font"></i><b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                        </ul>
                    </div>

                    <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i
                                class="fa fa-text-height"></i>&nbsp;<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a data-edit="fontSize 5">
                                    <p style="font-size:17px">Huge</p>
                                </a>
                            </li>
                            <li>
                                <a data-edit="fontSize 3">
                                    <p style="font-size:14px">Normal</p>
                                </a>
                            </li>
                            <li>
                                <a data-edit="fontSize 1">
                                    <p style="font-size:11px">Small</p>
                                </a>
                            </li>
                        </ul>
                    </div>

                    <div class="btn-group">
                        <a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="fa fa-bold"></i></a>
                        <a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="fa fa-italic"></i></a>
                        <a class="btn" data-edit="strikethrough" title="Strikethrough"><i
                                class="fa fa-strikethrough"></i></a>
                        <a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i
                                class="fa fa-underline"></i></a>
                    </div>

                    <div class="btn-group">
                        <a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i
                                class="fa fa-list-ul"></i></a>
                        <a class="btn" data-edit="insertorderedlist" title="Number list"><i
                                class="fa fa-list-ol"></i></a>
                        <a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i
                                class="fa fa-dedent"></i></a>
                        <a class="btn" data-edit="indent" title="Indent (Tab)"><i class="fa fa-indent"></i></a>
                    </div>

                    <div class="btn-group">
                        <a class="btn" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i
                                class="fa fa-align-left"></i></a>
                        <a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i
                                class="fa fa-align-center"></i></a>
                        <a class="btn" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i
                                class="fa fa-align-right"></i></a>
                        <a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i
                                class="fa fa-align-justify"></i></a>
                    </div>

                    <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i
                                class="fa fa-link"></i></a>
                        <div class="dropdown-menu input-append">
                            <input class="span2" placeholder="URL" type="text" data-edit="createLink" />
                            <button class="btn" type="button">Add</button>
                        </div>
                        <a class="btn" data-edit="unlink" title="Remove Hyperlink"><i class="fa fa-cut"></i></a>
                    </div>

                    <div class="btn-group">
                        <a class="btn" title="Insert picture (or just drag & drop)" id="pictureBtn"><i
                                class="fa fa-picture-o"></i></a>
                        <input type="file" data-role="magic-overlay" data-target="#pictureBtn"
                            data-edit="insertImage" />
                    </div>

                    <div class="btn-group">
                        <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="fa fa-undo"></i></a>
                        <a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="fa fa-repeat"></i></a>
                    </div>
                </div>

                <div id="editor-one" class="editor-wrapper"></div>
                <textarea name="content_raw" id="id_content_raw" style="display:none;">{{ form.content_raw }}</textarea>
            </div>


        </div>

        <div class="form-group">
            <div class="controls "> <input type="submit" name="submit" value="Submit" class="btn btn-primary"
                    id="submit-id-submit"> </div>
        </div>
    </form>
</div>


<script>
    $(document).ready(function () {
        $('#submit-id-submit').click(function () {
            $('#id_content_raw').val($('.editor-wrapper').html());

        });

        $('.editor-wrapper').html('{{ object.content_raw }}');
    });

</script>
{% endblock %}

forum/templates/forum/thread.html
{% extends 'forum/base.html' %}
{% load i18n %}
{% load forum_tags %}
{% load humanize %}
{% load crispy_forms_tags %}
{% load static %}

{% block breadcrumb %}


<li class="breadcrumb-item"><a href="{% url 'forum:index' %}">Forum</a></li>
<li class="breadcrumb-item">
    <a href="{% url 'forum:nodegroup' pk=thread.topic.node_group.pk %}">{{ thread.topic.node_group.title }}</a>
</li>
<li class="breadcrumb-item active"><a href="{% url 'forum:topic' pk=thread.topic.pk %}">{{ thread.topic.title }}</a>
</li>

{% endblock %}


{% block main_contain %}

{% include 'ForumInclude/threadpage.html' %}
{% endblock %}

forum/templates/forum/user_replies.html
{% extends 'forum/base.html' %}
{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{% url 'forum:index' %}">Forum</a></li>
<li class="breadcrumb-item"><a href="{% url 'forum:user_info' pk=user.pk %}">{{ user.username }}</a></li>
<li class="breadcrumb-item active">
    <a href="{% url 'forum:user_posts' pk=user.pk %}">Replies</a>
</li>


{% endblock %}

{% block main_contain %}
{% include 'ForumInclude/UserReplies.html' %}








{% endblock %}

forum/templates/forum/user_threads.html
{% extends 'forum/base.html' %}
{% load i18n %}
{% load forum_tags %}
{% load humanize %}
{% load static %}

{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{% url 'forum:index' %}">Forum</a></li>
<li class="breadcrumb-item"><a href="{% url 'forum:user_info' pk=user.pk %}">{{ user.username }}</a></li>
<li class="breadcrumb-item active">
    <a href="{% url 'forum:user_threads' pk=user.pk %}">Threads</a>
</li>

{% endblock %}

{% block main_contain %}
{% include 'ForumInclude/UserThread.html' %}
<!-- <div class="panel panel-default paper-shadow">
    <div class="panel panel-heading">
        <h2> Threads Created by {{ panel_title }} </h2>
    </div>

    {% if show_order %}
    <span class="pull-right ordering">
        Order:
        <span>
            <a href="{% change_thread_ordering request '-last_replied' %}">Last Replied</a>
        </span>
        <span>
            <a href="{% change_thread_ordering request '-pub_date' %}">thread Date</a>
        </span>
    </span>
    {% endif %}


   
    <ul class="list-group thread-list">
        {% for thread in threads %}
        <li class="list-group-item thread-entry">
            <div class="entry media">

                <a>
                    <img src="{{ request.user.Avatar }}" alt="..."
                        class=" avatar avatar-96wp-user-avatar wp-user-avatar-96 alignnone photo avatar-default " />
                </a>

                <h2 class=" thread_title">
                    <div class="media-body media-middle"> &nbsp;
                        <a href="{% url 'forum:thread' pk=thread.pk %}" class="entry-link">
                            {{ thread.title }}
                        </a>
                        <p class="entry-meta">
                            {% if thread.order <= 3 %}
                            <span class="meta">
                                <span class="label label-info meta-top">
                                    TOP
                                </span>
                            </span>
                            {% endif %}
                            <div class="topic_meta text-light text-caption">
                                <h5>
                                    <span class="meta meta-username">
                                        Topic:
                                        <a href="{% url 'forum:topic' thread.topic.pk %}" class="link-color">
                                            <span>
                                                {{ thread.topic.title }}
                                            </span>
                                        </a>
                                    </span> |
                                    <span class="meta meta-username ">
                                        posted by
                                        <a href="{% url 'forum:user_info' thread.user.pk %}" class="link-color">
                                            {{ thread.user.username }}
                                        </a>
                                    </span>
                                    <span class="meta meta-pub_date">
                                        {{ thread.pub_date | naturaltime }}
                                    </span>
                                    <span class="meta meta-last_replied hidden-xs">|
                                        {% trans "Last Replied" %}: {{ thread.last_replied | naturaltime }}
                                    </span>
                                </h5>
                            </div>
                        </p>

                        <div class="media-right media-middle">
                            <span class="pull-right badge">{{ thread.reply_count }} Reply</span>
                        </div>
                    </div>
                    </h5>
                </h2>
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="panel-footer">
        {% get_pagination %}
    </div>
</div> -->
{% endblock %}